

env:
  global:
    - TOOLS_DIR=$HOME/build_tools
    - GNAT_INSTALLER_PATH=$TOOLS_DIR/gnat-community-2018-20180528-x86_64-linux-bin
    - GNAT_PATH=$TOOLS_DIR/gnat-community-2018-x86_64-linux-bin

os:
  - linux

cache:
  yarn: true
  pip: true
  directories:
  - $HOME/build_tools
  - $HOME/.cache/pip

before_install:
 - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
 - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
 - sudo apt-get update -qq
 - sudo apt-get install -y -qq yarn graphviz

install: ./travis_install.sh

jobs:
  include:
    - stage: "Sphinx tests"
      language: python
      python: 3.6
      script:
        - cd frontend && PATH=$GNAT_PATH/bin:$PATH make test_content
    - stage: "Frontend unit tests"
      language: node_js
      node_js:
        - 12
      script:
        - cd frontend && yarn && yarn run test
    - stage: "Frontend build"
      language: python
      python: 3.6
      script:
        - cd frontend && PATH=$GNAT_PATH/bin:$PATH make SPHINXOPTS="-W" test_engine

# TODO: insert test stages for backend
