language: python

python:
  - "3.6"

env:
  global:
    - TOOLS_DIR=$HOME/build_tools
    - GNAT_INSTALLER_PATH=$TOOLS_DIR/gnat-community-2019-20190517-x86_64-linux-bin
    - GNAT_PATH=$TOOLS_DIR/gnat-community-2019-x86_64-linux-bin

os:
  - linux

dist: bionic

cache:
  directories:
  - $HOME/build_tools
  - $HOME/.cache/pip

git:
  submodules:
    false

before_install:
 - "sudo apt-get install graphviz"

install: cd engine && ./travis_install.sh

script: ./travis_script.sh
