language: python

python:
  - "2.7"

env:
  global:
    - TOOLS_DIR=$HOME/build_tools
    - GNAT_INSTALLER_PATH=$TOOLS_DIR/gnat-community-2019-20190517-x86_64-linux-bin
    - GNAT_PATH=$TOOLS_DIR/gnat-community-2019-x86_64-linux-bin

os:
  - linux

dist: bionic

cache:
  directories:
  - $HOME/build_tools
  - $HOME/.cache/pip

git:
  submodules:
    false

before_install:
 - "sudo apt-get install graphviz texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra latexmk texlive-xetex fonts-lmodern fonts-open-sans fonts-dejavu"

install: cd engine && ./travis_install.sh

script: ./travis_script.sh
