#cloud-config
package_upgrade: false

# Add users
users:
  - default
  - name: unprivileged
    system: true
  - name: runner
    sudo:  ALL=(unprivileged) NOPASSWD:ALL

# Write preloader file
write_files:
  - path: /root/preloader.c
    content: |
      #include <unistd.h>
      #include <stdio.h>

      pid_t fork(void) {
        printf("fork not allowed\n");
         _exit(1);
      }

      pid_t vfork(void) {
         printf("vfork not allowed\n");
         _exit(1);
      }

      int system(char* text) {
        printf("system not allowed\n");
         _exit(1);
      }

      int execve(const char *filename, char *const argv[],
             char *const envp[]) {
        printf("execve not allowed\n");
        _exit(1);
      }

network:
  config: disabled

# Run command on first boot only
runcmd:
  # Install community
  - ["mkdir", "-p", "/workspace/sessions"]
  - ["chown", "runner", "/workspace/sessions"]
  - ["gcc", "-shared", "-o", "/preloader.so", "-fPIC", "/root/preloader.c"]
  - ["git", "clone", "https://github.com/AdaCore/gnat_community_install_script.git"]
  #- ["rm", "-f", "/root/package"]
  - ["wget", "-nv", "https://community.download.adacore.com/v1/0cd3e2a668332613b522d9612ffa27ef3eb0815b?filename=gnat-community-2019-20190517-x86_64-linux-bin", "-O", "/root/package"]
  - ["sh", "gnat_community_install_script/install_package.sh", "/root/package", "/gnat"]
  # Prevent unprivileged from writing to /tmp
  - ["chmod", "775", "/tmp"]
  - ["chmod", "775", "/var/tmp"]
  - ["chgrp", "runner", "/tmp"]
  - ["chgrp", "runner", "/var/tmp"]
  # deactivate network
  - ["ifconfig", "eth0", "down"]

# Install packages
packages:
  - make
  - gcc
  - libfontconfig
  - libx11-xcb-dev
